version: '3.8'

services:
    social_app_v2:
        image: mezmerizxd/social-app-v2
        restart: always
        container_name: 'social-app-v2'
        volumes:
            - .:/usr/src/social-app-v2/
            - '/usr/src/social-app-v2/node_modules'
        working_dir: /usr/src/social-app-v2
        environment:
            - PORT=3001
            - SOCKET_PORT=3002
            - ENABLE_MYSQL=false
            - ENABLE_MONGODB=false
            - ENABLE_FIREBASE=false
        command: sh -c "yarn && yarn build && yarn start"
        ports:
            - 3001:3001
            - 3002:3002

    ########### PRODUCTION SERVICES ###########
    # nginx:
    #     build:
    #         context: .
    #         dockerfile: nginx/Dockerfile
    #     depends_on:
    #         - app
    #     restart: always
    #     image: nginx
    #     container_name: 'nginx'
    #     ports:
    #         - '80:80'
    #         - '443:443'

    # mongodb:
    #     image: mongo:5.0
    #     container_name: mongodb
    #     restart: always
    #     environment:
    #         - MONGO_INITDB_ROOT_USERNAME=root
    #         - MONGO_INITDB_ROOT_PASSWORD=root
    #     volumes:
    #         - /data/db
    #     ports:
    #         - '27017:27017'

    # mysql:
    #     image: mysql:5.7
    #     container_name: mysql
    #     restart: always
    #     environment:
    #         - MYSQL_ROOT_PASSWORD=root
    #         - MYSQL_DATABASE=social_app_v2
    #         - MYSQL_USER=social_app
    #         - MYSQL_PASSWORD=groot
    #     volumes:
    #         - /var/lib/mysql
    #     ports:
    #         - '3306:3306'
