name: Development Node.js CI

on:
    pull_request:
        branches: development

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - name: Checkout
              uses: actions/checkout@v3
