name: Production Node.js CI

on:
    push:
        branches: main

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3

            - name: Docker build & push
            - uses: mr-smithers-excellent/docker-build-push@v4
            - with:
                  - image: mezmerizxd/social-app-v2
                  - registry: docker.io
                  - username: ${{ secrets.DOCKER_USERNAME }}
                  - passwords: ${{ secrets.DOCKER_PASSWORD }}

            # - name: Use Node.js ${{ matrix.node-version }}
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: ${{ matrix.node-version }}
            #       cache: 'yarn'
            # - run: yarn --production=true
            # - run: yarn build
            # - run: yarn format
